name: 'heroku-vault'
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: heroku-vault-deploy
    runs-on: ubuntu-latest
    environment: PROD
    defaults:
      run:
        shell: bash
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Heroku Login
        run: |
          touch ~/.netrc
          echo "machine api.heroku.com" >> ~/.netrc
          echo "  login ${{ secrets.HEROKU_LOGIN }}" >> ~/.netrc
          echo "  password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
          echo "machine git.heroku.com" >> ~/.netrc
          echo "  login ${{ secrets.HEROKU_LOGIN }}" >> ~/.netrc
          echo "  password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh